services:
  - type: web
    name: gadash-bot
    env: python
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2
