"""initial multi-tenant schema

Revision ID: d89d91688345
Revises: 
Create Date: 2026-09-08 10:16:44.597445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89d91688345'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('user', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'uid', name='uq_field_tenant_uid')
    )
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fields_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rates',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('revenue_rate', sa.Float(), nullable=False),
    sa.Column('cost_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'task')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chat_id', name='uq_subscriber_tenant_chat')
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('work_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=200), nullable=True),
    sa.Column('crop', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=True),
    sa.Column('hours', sa.String(length=50), nullable=True),
    sa.Column('tool', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entered_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_entries', schema=None) as batch_op:
        batch_op.create_index('ix_work_entries_tenant_date', ['tenant_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_entries_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telegram_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_worker_tenant_name')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workers_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_workers_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_workers_telegram_id'))

    op.drop_table('workers')
    with op.batch_alter_table('work_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_entries_tenant_id'))
        batch_op.drop_index('ix_work_entries_tenant_date')

    op.drop_table('work_entries')
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_tenant_id'))

    op.drop_table('subscribers')
    op.drop_table('rates')
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managers_tenant_id'))

    op.drop_table('managers')
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fields_tenant_id'))

    op.drop_table('fields')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))

    op.drop_table('audit_log')
    op.drop_table('tenants')
    # ### end Alembic commands ###
