"""add worker whatsapp_number

Revision ID: eb088856f357
Revises: 72ac424b9719
Create Date: 2026-09-09 09:43:55.930421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb088856f357'
down_revision = '72ac424b9719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_workers_whatsapp_number'), ['whatsapp_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_whatsapp_number'))
        batch_op.drop_column('whatsapp_number')

    # ### end Alembic commands ###
